version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
hooks:
  BeforeInstall:
    - location: script/Stop_Server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/Start_Server.sh
      timeout: 300
      runas: root
